name: "main"

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'

jobs:
  c2cs_runtime-job:
    name: ".NET: C2CS.Runtime"
    runs-on: ubuntu-latest
    steps:
      - uses: bottlenoselabs/github-actions-dotnet@v1
        with:
          repository: '${{ github.repository }}'
          solution-or-project: './src/cs/production/C2CS.Runtime/C2CS.Runtime.csproj'
          dotnet-sdk-version: '6.0.x'
          is-enabled-pack: 'true'
          publish-environment: 'staging'
          myget-access-token: '${{ secrets.MYGET_ACCESS_TOKEN }}'
          nuget-access-token: '${{ secrets.NUGET_ACCESS_TOKEN }}'
  c2cs-job:
    name: ".NET: C2CS"
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: bottlenoselabs/github-actions-dotnet@v1
        with:
          repository: '${{ github.repository }}'
          solution-or-project: './src/cs/production/C2CS/C2CS.csproj'
          dotnet-sdk-version: '6.0.x'
          is-enabled-pack: ${{ matrix.os == 'ubuntu-latest' }}
          publish-environment: 'staging'
          myget-access-token: '${{ secrets.MYGET_ACCESS_TOKEN }}'
          nuget-access-token: '${{ secrets.NUGET_ACCESS_TOKEN }}'

