name: "main"

on:
  push:
    paths-ignore:
      - '**.md'
  release:
    types: [released]

jobs:
  dotnet-job:
    name: ".NET"
    runs-on: ubuntu-latest
    steps:
      - uses: bottlenoselabs/github-actions-dotnet@v2
        with:
          repository: '${{ github.repository }}'
          dotnet-sdk-version: '6.0.x'
          is-enabled-pack: 'true'
          upload-myget-org: "${{ github.event_name == 'push' || github.event_name == '' }}"
          upload-nuget-org: "${{ github.event_name == 'release' }}"
          myget-access-token: '${{ secrets.MYGET_ACCESS_TOKEN }}'
          nuget-access-token: '${{ secrets.NUGET_ACCESS_TOKEN }}'

