name: "main"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  dotnet-job:
    name: ".NET"
    runs-on: ubuntu-latest
    steps:
      - uses: bottlenoselabs/github-actions-dotnet@v2
        with:
          repository: '${{ github.repository }}'
          dotnet-sdk-version: '6.0.x'
          is-enabled-pack: 'true'
          myget-access-token: '${{ secrets.MYGET_ACCESS_TOKEN }}'
          nuget-access-token: '${{ secrets.NUGET_ACCESS_TOKEN }}'

