name: "main"

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'

jobs:
  dotnet-job:
    name: "Build, test, pack, and deploy .NET"
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: bottlenoselabs/github-actions-dotnet@v1
        with:
          repository: '${{ github.repository }}'
          dotnet-sdk-version: '6.0.x'
          is-enabled-pack: ${{ matrix.os == 'ubuntu-latest' }}
          publish-environment: 'staging'
          myget-access-token: '${{ secrets.MYGET_ACCESS_TOKEN }}'
          nuget-access-token: '${{ secrets.NUGET_ACCESS_TOKEN }}'

